### ISSUE TITLE
网络请求回来的数据怎么处理？

### ISSUE THREAD

**Issue by brave723** [rickytan/RTComponentTableView#3]
网络请求回来的数据怎么处理？看你的demo都是简单的数据！

**Comment by rickytan** [comment]
多个 component 的数据是一起返回的，还是分接口返回的？
1. 一起返回。在 **VC** 中请求，拿到数据后，一个个传到 component 中，再 `- reloadData`
2. 分接口返回。每个 component 暴露一个 `- requestData` 类似的方法，在 **VC** 中调用它，每个 component 请求返回后自己处理自己的数据，并调 `[self.tableView reloadData]`，这时 **tableView** 会 `reload` 多次
