### ISSUE TITLE
高度自适应

### ISSUE THREAD

**Issue by emulateStep** [rickytan/RTComponentTableView#4]
1.如果底层是collection，主要是竖着滑动，某个分区出来一个横着滑动的collection？
2.如果出现类似京东评论那样的cell，文字+collection图片，自适应，会不会比较麻烦？

**Comment by rickytan** [comment]
1. 您可以在某个 indexPath 上的 cell.contentView 中加 collectionView，以实现一个单独的横滚
2. 变高问题一直是 iOS 的痛点，是有点麻烦的
    * `UITableVew` 上有 [UITableView-FDTemplateLayoutCell](https://github.com/forkingdog/UITableView-FDTemplateLayoutCell)，且 iOS 8 以后可以用 **UITableViewAutomaticDimension**
    * `UICollectionView` 我做了个类似的 [UICollectionViewCellAutomaticDimension](https://github.com/rickytan/UICollectionViewCellAutomaticDimension)，使用说明还没写。或者用 iOS 10 以后自带的 **UICollectionViewFlowLayoutAutomaticSize**
